### ISSUE TITLE
how to cite PyMCubes

### ISSUE THREAD

**Issue by gianthk** [pmneila/PyMCubes#41]
would be nice to know how to cite the use of this nice package!

**Comment by pmneila** [comment]
Hi, @gianthk 

Thank you for asking :). While it is not required that you cite the package, I would greatly appreciate it if you could do so.

Here you have a few alternatives depending on your writing tool.

1. In plain text, you can use 
> Pablo Márquez Neila, _PyMCubes: marching cubes for Python_, `https://github.com/pmneila/PyMCubes`, version 0.1.4, 2013.

(update the version number accordingly)

2. If you use BibTex, you can include it in the bib database with
```
@misc{pymcubes,
  author = {{Pablo M\'{a}rquez Neila}},
  title = {{PyMCubes}: marching cubes for {P}ython},
  note = {\texttt{https://github.com/pmneila/PyMCubes}, version 0.1.4},
  year = {2023},
}
```

3. Alternatively, if you use the `biblatex` package:
```
@software{pymcubes,
  author = {{Pablo M\'{a}rquez Neila}},
  title = {{PyMCubes}: marching cubes for {P}ython},
  url = {https://github.com/pmneila/PyMCubes},
  version = {0.1.4},
  date = {2023-01-15},
}
```

I hope that is helpful; please let me know otherwise. I will include a section in the `README` file with this information for future reference.

Best
